[metadata]
name = elguason
version = 1.0.0
author = Ambro17
author_email = ambro17.1@gmail.com
description = Facturas de Monotributo AFIP as a service
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/Ambro17/elguason

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.8

[options.packages.find]
where = src